// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;
using System.Resources;

[assembly: AssemblyTitle("PingLogger")]
[assembly: AssemblyDescription("Advanced multi-threaded ping logging application")]
[assembly: AssemblyVersion("2.1.0.12")]
[assembly: NeutralResourcesLanguage("en-US")]
