# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  project: 'PingLogger.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  outputDirectory: '$(Pipeline.Workspace)/s/bin/Release/net5.0/ClickOnce'

steps:
- task: NuGetToolInstaller@1

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build'

- script: dotnet publish  $(project) --configuration $(buildConfiguration) /p:PublishProfile=ClickOnceProfile
  displayName: 'dotnet publish'

- task: CopyFiles@2
  displayName: 'Copy setup to artifact'
  inputs:
    SourceFolder: '$(outputDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  displayName: 'publish artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'

- task: FtpUpload@2
  inputs:
    credentialsOption: 'serviceEndpoint'
    serverEndpoint: 'PingLogger FTP'
    rootDirectory: '$(Build.ArtifactStagingDirectory)'
    filePatterns: '**'
    remoteDirectory: '/clickonce'
    clean: false
    cleanContents: true
    preservePaths: true
    trustSSL: true