# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  project: 'PingLogger.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build'

- script: dotnet publish $(project) /p:PublishProfile=ClickOnceProfile
  displayName: 'dotnet publish'

- task: PublishPipelineArtifact@1
  displayName: 'publish artifact'
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/bin/Release/net5.0/publish/ClickOnce/'
    publishLocation: 'pipeline'

- task: FtpUpload@2
  inputs:
    credentialsOption: 'serviceEndpoint'
    serverEndpoint: 'PingLogger FTP'
    rootDirectory: 'bin\Release\net5.0\app.publish'
    filePatterns: '**'
    remoteDirectory: '/clickonce'
    clean: false
    cleanContents: true
    preservePaths: true
    trustSSL: true