// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyTitle("PingLogger")]
[assembly: AssemblyDescription("Advanced multi-threaded ping logging application")]
[assembly: AssemblyVersion("2.0.0.273")]
[assembly: AssemblyFileVersion("2.0.0.273")]
