name: pinglogger
base: core18
version: '3.0.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: Advanced cross-platform ping logger
description: |
 Cross-platform Ping Logger capable of pinging
 multiple hosts at once, with variable timers,
 packet size, warning thresholds, and timeouts

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  pinglogger:
    command: PingLogger

parts:
  pinglogger:
    source: .
    plugin: dotnet